export const BANNER_URI = "https://shemashop.vercel.app/static/media/men2.e2bb29b95d23d0e4e42f.png"
export const CATEGORIES_URI = "https://fakestoreapi.com/products/categories"
export const MENS_CATEGORIES_IMAGE_URI = "https://media.istockphoto.com/id/1065840316/photo/attractive-businessmen-on-the-street.jpg?s=612x612&w=0&k=20&c=8-tpELzQrwsNPzdqJYO03jFSdD0PPemWQ2kKTouEra4="
export const WOMENS_CATEGORIES_IMAGE_URI = "https://img.freepik.com/premium-photo/beautiful-asian-woman-carrying-colorful-bags-shopping-online-with-mobile-phone_8087-3877.jpg"
export const ELECTRONICS_IMAGE_URI = "https://thumbs.dreamstime.com/b/saint-petersburg-russia-circa-may-goods-display-sony-store-galeria-shopping-center-electronics-store-134641471.jpg"
export const JEWELLERY_IMAGE_URI = "https://c8.alamy.com/comp/M7AR7M/china-hong-kong-kowloon-jewellery-shop-window-display-of-gold-jewellery-M7AR7M.jpg"
export const FEATURED_ITEMS_URI = "https://fakestoreapi.com/products"
export const MENS_CATEGORY_URI = "https://fakestoreapi.com/products/category/men's clothing"
export const WOMENS_CATEGORY_URI = "https://fakestoreapi.com/products/category/women's clothing"
export const JEWELLERY_CATEGORY_URI = "https://fakestoreapi.com/products/category/jewelery"
export const ELECTRONICS_CATEGORY_URI = "https://fakestoreapi.com/products/category/electronics"